// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3UAVLsArqTHIQKqJOZVrAgBW2Vdcme2A',
    appId: '1:129952328812:web:e7ee95bb64ec150a837c49',
    messagingSenderId: '129952328812',
    projectId: 'qlthuvien-ff034',
    authDomain: 'qlthuvien-ff034.firebaseapp.com',
    storageBucket: 'qlthuvien-ff034.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYSvQ31wrszjOjjHUxKw33ZsmNcJerkKU',
    appId: '1:129952328812:android:51c38c3261a62c2d837c49',
    messagingSenderId: '129952328812',
    projectId: 'qlthuvien-ff034',
    storageBucket: 'qlthuvien-ff034.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdnT2vDwEgJR4nDliiCjHUKvlvwKJj-zw',
    appId: '1:129952328812:ios:35be8f6a50c6ee89837c49',
    messagingSenderId: '129952328812',
    projectId: 'qlthuvien-ff034',
    storageBucket: 'qlthuvien-ff034.appspot.com',
    iosBundleId: 'com.example.qlthuvien',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdnT2vDwEgJR4nDliiCjHUKvlvwKJj-zw',
    appId: '1:129952328812:ios:35be8f6a50c6ee89837c49',
    messagingSenderId: '129952328812',
    projectId: 'qlthuvien-ff034',
    storageBucket: 'qlthuvien-ff034.appspot.com',
    iosBundleId: 'com.example.qlthuvien',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3UAVLsArqTHIQKqJOZVrAgBW2Vdcme2A',
    appId: '1:129952328812:web:d55ae975b19b0f09837c49',
    messagingSenderId: '129952328812',
    projectId: 'qlthuvien-ff034',
    authDomain: 'qlthuvien-ff034.firebaseapp.com',
    storageBucket: 'qlthuvien-ff034.appspot.com',
  );
}
